name: Dev Release
on:
  push:
    branches: [dev]

permissions:
  contents: write # allow pushing commits & tags
  packages: write # allow npm publish
  pull-requests: write # allow commenting on PRs

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install dependencies and build
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Release to @next tag
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
