name: Release Preview
on:
  pull_request:
    branches: [main]
jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci --legacy-peer-deps && npm run build

      - name: Generate Release Notes
        run: |
          # Create temporary .releaserc.json for PR preview
          echo '{
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator"
            ]
          }' > .releaserc.preview.json
          
          # Run semantic-release with the preview config
          npx semantic-release --dry-run --extends ./.releaserc.preview.json --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add PR Comment with Next Release
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            try {
              const releaseOutput = fs.readFileSync('release-notes.md', 'utf8');
              const body = `## 🚀 Release Preview\n\n${releaseOutput || 'No changes detected that would trigger a release.'}`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            } catch(e) {
              console.log('No release notes found or error generating comment:', e);
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## 🚀 Release Preview\n\nNo changes detected that would trigger a release, or there was an error generating the preview.'
              });
            }
