name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write # allow pushing commits & tags
  packages: write # allow npm publish (optional)
  pull-requests: write # allow commenting on PRs

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install dependencies and build
        run: |
          # install dependencies and build the project
          # --legacy-peer-deps is needed for some packages that have peer dependency issues
          # see https://docs.npmjs.com/cli/v7/commands/npm-install#legacy-peer-deps
          npm ci --legacy-peer-deps && npm run build

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
