name: Release Preview
on:
  pull_request:
    branches: [main]

# Define required permissions explicitly
permissions:
  contents: read
  pull-requests: write

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci --legacy-peer-deps && npm run build

      - name: Generate Release Notes
        run: |
          # Create temporary .releaserc.json for PR preview
          echo '{
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator"
            ]
          }' > .releaserc.preview.json

          # Run semantic-release with the preview config and output to log
          echo "Running release preview with dry run..."
          npx semantic-release --dry-run --extends ./.releaserc.preview.json --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
